# Generated by Django 4.0.4 on 2022-06-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
